### ISSUE TITLE
所提供代码似乎只支持分类任务，请问能否上传标注命名实体识别任务的代码呢？

### ISSUE THREAD

**Issue by fire66** [Justherozen/FreeAL#2]

**Comment by jskksd** [comment]
大佬能给一下配置环境吗

**Comment by Justherozen** [comment]
Thank you for your question. The code frameworks and details for text classification and the NER part differ significantly due to the nature of the tasks. We will integrate and unify both before uploading them later.

**Comment by Justherozen** [comment]
Thank you for your question. The code frameworks and details for text classification and the NER part differ significantly due to the nature of the tasks. We will integrate and unify both before uploading them later.
